# Generated by Django 6.0.2 on 2026-02-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_recipe_video_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodapp.category'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_recipes/main/'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_recipes/videos/'),
        ),
        migrations.CreateModel(
            name='UserRecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_recipes/gallery/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='foodapp.userrecipe')),
            ],
        ),
    ]
